<?php
require __DIR__.'/bootstrap.php';require_auth();if(!can('payments.view')){http_response_code(403);exit('Forbidden');}require __DIR__.'/partials.php';
$id=(int)($_GET['id']??0);$s=$db->prepare('SELECT a.*,c.customer_code,c.name customer,c.phone,c.address,p.item_code,p.name product,p.unit,u.display_name received_by FROM customer_advances a JOIN customers c ON c.id=a.customer_id LEFT JOIN products p ON p.id=a.product_id JOIN users u ON u.id=a.created_by WHERE a.id=?');$s->execute([$id]);$a=$s->fetch();if(!$a){http_response_code(404);exit('Advance not found');}
$s=$db->prepare('SELECT x.*,s.sale_no FROM customer_advance_applications x JOIN sales s ON s.id=x.sale_id WHERE x.advance_id=? ORDER BY x.id');$s->execute([$id]);$applications=$s->fetchAll();
$expectedTotal=$a['product']?(float)$a['reserved_quantity']*(float)$a['expected_unit_price']:0;$reservedAvailable=$a['product']?min((float)$a['remaining_amount'],$expectedTotal):0;$extraForFuture=$a['product']?max(0,(float)$a['remaining_amount']-$expectedTotal):(float)$a['remaining_amount'];$expectedStillDue=$a['product']?max(0,$expectedTotal-(float)$a['amount']):0;
page_start('Advance Receipt '.$a['advance_no'],'advances.php');?>
<div class="invoice-actions"><a class="btn secondary" href="advances.php">← Customer Advances</a><button class="btn primary" onclick="window.print()">Print / Save PDF</button></div>
<section class="panel advance-receipt"><header><div><img src="assets/supun-traders-logo.png" alt="Supun Traders"><p>114, Second Cross Street, Pettah, Colombo 11</p></div><div class="right"><span class="eyebrow">Customer Advance Receipt</span><h2><?=e($a['advance_no'])?></h2><p><?=date('d F Y, h:i A',strtotime($a['received_at']))?></p></div></header>
<div class="receipt-grid"><div><span>Received From</span><b><?=e($a['customer'])?></b><p><?=e($a['phone'].' '.$a['address'])?></p></div><div><span>Received Using</span><b><?=e(ucwords(str_replace('_',' ',$a['method'])))?></b><p><?=e($a['reference_no']?:'No reference')?></p></div><div><span>Status</span><b><?=e(ucwords(str_replace('_',' ',$a['status'])))?></b></div></div>
<div class="advance-total"><span>Advance Received</span><strong><?=money($a['amount'])?></strong></div>
<div class="reserved-detail"><h3>Purpose / Reserved Item</h3><?php if($a['product']):?><p><b><?=e($a['item_code'].' - '.$a['product'])?></b></p><p><?=e($a['reserved_quantity'].' '.($a['unit']?:'PCS'))?> · Expected unit price <?=money($a['expected_unit_price'])?></p><?php else:?><p>General customer advance — item not decided.</p><?php endif;?><p>Notes: <?=e($a['notes']?:'None')?></p></div>
<?php if($a['product']):?><div class="receipt-order-total"><p><span>Expected total price</span><b><?=money($expectedTotal)?></b></p><p><span>Reserved for this order</span><b><?=money($reservedAvailable)?></b></p><?php if($extraForFuture>0):?><p class="future-extra"><span>Extra kept for future purchases</span><strong><?=money($extraForFuture)?></strong></p><?php elseif($expectedStillDue>0):?><p><span>Expected amount still to pay</span><b><?=money($expectedStillDue)?></b></p><?php endif;?></div><?php endif;?>
<div class="advance-balance"><p><span>Applied to invoices</span><b><?=money((float)$a['amount']-(float)$a['remaining_amount'])?></b></p><?php foreach($applications as $x):?><p><span><?=e($x['sale_no'])?></span><b><?=money($x['amount'])?></b></p><?php endforeach;?><p class="grand"><span>Total Advance Still Available</span><strong><?=money($a['remaining_amount'])?></strong></p></div>
<p class="receipt-note">Extra money remains in the customer account for future purchases. This receipt is not sales revenue and does not reduce stock until a final sale invoice is created.</p></section>
<style>.invoice-actions{display:flex;justify-content:space-between;margin-bottom:16px}.advance-receipt{max-width:950px;margin:auto;padding:30px}.advance-receipt header{display:flex;justify-content:space-between;border-bottom:2px solid #17583f;padding-bottom:20px}.advance-receipt header img{width:190px}.advance-receipt header p{color:#718078}.receipt-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:18px;padding:24px 0}.receipt-grid span{display:block;font-size:10px;text-transform:uppercase;color:#718078}.receipt-grid p{color:#718078}.advance-total{display:flex;justify-content:space-between;align-items:center;padding:22px;background:#e8f4e5;border-radius:12px}.advance-total strong{font-size:30px}.reserved-detail{padding:22px 0}.receipt-order-total{background:#f4f8f1;border-radius:10px;padding:14px 18px;margin-bottom:22px}.receipt-order-total p{display:flex;justify-content:space-between;margin:7px 0}.receipt-order-total .future-extra{border-top:1px solid #d4ded1;padding-top:11px;color:#177449}.advance-balance{margin-left:auto;max-width:430px}.advance-balance p{display:flex;justify-content:space-between}.advance-balance .grand{border-top:2px solid;padding-top:14px;font-size:19px}.receipt-note{margin-top:25px;padding:14px;background:#fff4dc;border-left:4px solid #c88820}@media print{.sidebar,.topbar,.invoice-actions{display:none!important}.app{margin:0!important;width:100%!important}.content{padding:0!important}.advance-receipt{border:0!important;box-shadow:none!important}}</style>
<?php page_end();
