<?php
require __DIR__.'/bootstrap.php';require_auth();
if(!can('customers.view')){http_response_code(403);exit('Forbidden');}
header('Content-Type: application/json; charset=utf-8');
$customerId=(int)($_GET['customer_id']??0);
$s=$db->prepare('SELECT a.id,a.advance_no,a.received_at,a.method,a.reference_no,a.amount,a.remaining_amount,a.status,a.reserved_quantity,a.expected_unit_price,p.item_code,p.name product,p.unit,COALESCE((SELECT SUM(x.amount) FROM customer_advance_applications x WHERE x.advance_id=a.id),0) applied_amount FROM customer_advances a LEFT JOIN products p ON p.id=a.product_id WHERE a.customer_id=? ORDER BY a.received_at DESC,a.id DESC');
$s->execute([$customerId]);$rows=$s->fetchAll();$details=[];$available=$reserved=$extra=$received=$applied=0;
foreach($rows as $row){$expected=$row['product']?(float)$row['reserved_quantity']*(float)$row['expected_unit_price']:0;$remaining=(float)$row['remaining_amount'];$isOpen=in_array($row['status'],['open','partially_applied'],true);$reservedNow=$isOpen&&$row['product']?min($remaining,$expected):0;$extraNow=$isOpen?($row['product']?max(0,$remaining-$expected):$remaining):0;$received+=(float)$row['amount'];$applied+=(float)$row['applied_amount'];$available+=$isOpen?$remaining:0;$reserved+=$reservedNow;$extra+=$extraNow;$details[]=['id'=>(int)$row['id'],'advance_no'=>$row['advance_no'],'received_at'=>$row['received_at'],'method'=>$row['method'],'reference_no'=>$row['reference_no'],'amount'=>(float)$row['amount'],'applied_amount'=>(float)$row['applied_amount'],'remaining_amount'=>$remaining,'status'=>$row['status'],'item_code'=>$row['item_code'],'product'=>$row['product'],'unit'=>$row['unit'],'reserved_quantity'=>(float)$row['reserved_quantity'],'expected_unit_price'=>(float)$row['expected_unit_price'],'expected_total'=>$expected,'reserved_for_order'=>$reservedNow,'extra_for_future'=>$extraNow];}
echo json_encode(['summary'=>['received'=>$received,'applied'=>$applied,'available'=>$available,'reserved'=>$reserved,'extra'=>$extra],'advances'=>$details],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
