<?php
require __DIR__ . '/bootstrap.php'; require_auth(); require __DIR__ . '/partials.php';
$today = $db->query("SELECT COALESCE(SUM(total),0) sales, COALESCE(SUM(gross_profit),0) profit FROM (SELECT s.id,s.total,SUM(si.gross_profit) gross_profit FROM sales s JOIN sale_items si ON si.sale_id=s.id WHERE DATE(s.sale_date)=CURDATE() AND s.status NOT IN ('cancelled','returned') GROUP BY s.id) x")->fetch() ?: ['sales'=>0,'profit'=>0];
$month = $db->query("SELECT COALESCE(SUM(total),0) total FROM sales WHERE YEAR(sale_date)=YEAR(CURDATE()) AND MONTH(sale_date)=MONTH(CURDATE()) AND status NOT IN ('cancelled','returned')")->fetchColumn();
$receivables = $db->query("SELECT COALESCE(SUM(balance),0) FROM sales WHERE payment_type='credit' AND status IN ('unpaid','partially_paid','overdue')")->fetchColumn();
$stockValue = $db->query("SELECT COALESCE(SUM(current_stock*avg_cost),0) FROM products WHERE status='active'")->fetchColumn();
$lowStock = $db->query("SELECT COUNT(*) FROM products WHERE status='active' AND current_stock<=minimum_stock")->fetchColumn();
$recent = $db->query("SELECT s.sale_no,s.sale_date,COALESCE(c.name,'Walk-in Customer') customer,s.sale_type,s.payment_type,s.total,s.status FROM sales s LEFT JOIN customers c ON c.id=s.customer_id ORDER BY s.id DESC LIMIT 6")->fetchAll();
$top = $db->query("SELECT p.name,SUM(si.quantity) qty,SUM(si.line_total) revenue FROM sale_items si JOIN products p ON p.id=si.product_id JOIN sales s ON s.id=si.sale_id WHERE s.sale_date>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) AND s.status NOT IN ('cancelled','returned') GROUP BY p.id ORDER BY revenue DESC LIMIT 5")->fetchAll();
page_start('Business overview','index.php'); ?>
<section class="hero"><div><span class="eyebrow">Live business pulse</span><h2>Good <?=date('H')<12?'morning':(date('H')<17?'afternoon':'evening')?>, <?=e(explode(' ',user()['display_name'])[0])?>.</h2><p>Here’s what is happening across sales, credit and inventory.</p></div><div class="hero-meta"><span>Financial period</span><b><?=date('F Y')?></b></div></section>
<section class="kpi-grid"><article class="kpi"><div class="kpi-top"><span>Today’s sales</span><i class="good">↗</i></div><strong><?=money($today['sales'])?></strong><small>Across cash and credit</small></article><article class="kpi"><div class="kpi-top"><span>Monthly sales</span><i>◫</i></div><strong><?=money($month)?></strong><small><?=date('F')?> revenue</small></article><article class="kpi"><div class="kpi-top"><span>Receivables</span><i class="warn">!</i></div><strong><?=money($receivables)?></strong><small>Outstanding customer credit</small></article><article class="kpi"><div class="kpi-top"><span>Stock at cost</span><i>▦</i></div><strong><?=money($stockValue)?></strong><small><?=$lowStock?> low-stock item<?=$lowStock==1?'':'s'?></small></article></section>
<section class="split"><article class="panel chart-panel"><div class="panel-head"><div><span class="eyebrow">Performance</span><h3>Sales at a glance</h3></div><select><option>Last 7 days</option></select></div><div class="empty-chart"><div class="chart-bars"><i style="height:35%"></i><i style="height:56%"></i><i style="height:46%"></i><i style="height:78%"></i><i style="height:64%"></i><i style="height:92%"></i><i style="height:71%"></i></div><small>Chart activates as transactions are recorded</small></div></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">Inventory</span><h3>Top products</h3></div><a href="reports.php">View report →</a></div><?php if(!$top):?><div class="empty-state"><b>No sales data yet</b><span>Your best-selling products will appear here.</span></div><?php else:?><div class="rank-list"><?php foreach($top as $i=>$row):?><div><b><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></b><span><?=e($row['name'])?><small><?=e($row['qty'])?> units</small></span><strong><?=money($row['revenue'])?></strong></div><?php endforeach;?></div><?php endif;?></article></section>
<section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">Latest activity</span><h3>Recent sales</h3></div><a href="reports.php">All transactions →</a></div><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Type</th><th>Date</th><th>Status</th><th class="right">Total</th></tr></thead><tbody><?php if(!$recent):?><tr><td colspan="6"><div class="empty-state compact"><b>No sales recorded</b><span>Create your first sale to begin.</span></div></td></tr><?php endif;?><?php foreach($recent as $row):?><tr><td><b><?=e($row['sale_no'])?></b></td><td><?=e($row['customer'])?></td><td><span class="tag"><?=e(ucfirst($row['sale_type']))?></span> <?=e(ucfirst($row['payment_type']))?></td><td><?=date('d M, H:i',strtotime($row['sale_date']))?></td><td><span class="status <?=e($row['status'])?>"><?=e(str_replace('_',' ',$row['status']))?></span></td><td class="right"><b><?=money($row['total'])?></b></td></tr><?php endforeach;?></tbody></table></div></section>
<?php page_end();

