<?php
require __DIR__.'/bootstrap.php';require_auth();if(!can('reports.view')){http_response_code(403);exit('Forbidden');}require __DIR__.'/partials.php';
$rows=$db->query('SELECT p.item_code,p.name,COALESCE(c.name,"Uncategorised") category,p.unit,p.current_stock,p.avg_cost,p.retail_price,p.wholesale_price,(p.current_stock*p.avg_cost) stock_cost,(p.current_stock*p.retail_price) retail_income,(p.current_stock*p.wholesale_price) wholesale_income,(p.current_stock*(p.retail_price-p.avg_cost)) retail_profit,(p.current_stock*(p.wholesale_price-p.avg_cost)) wholesale_profit FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.status="active" AND p.current_stock>0 ORDER BY retail_income DESC')->fetchAll();
$sum=fn(string $key)=>array_sum(array_map(fn($row)=>(float)$row[$key],$rows));$units=$sum('current_stock');$cost=$sum('stock_cost');$retail=$sum('retail_income');$wholesale=$sum('wholesale_income');$retailProfit=$sum('retail_profit');$wholesaleProfit=$sum('wholesale_profit');
page_start('Predicted Stock Income','inventory_forecast.php');?>
<section class="forecast-head"><div><span class="eyebrow">If every item currently in stock is sold</span><h2>Full Predicted Income</h2><p>This is a forecast, not money already earned. Retail and wholesale outcomes are shown separately.</p></div><button class="btn primary" onclick="window.print()">Print / Save PDF</button></section>
<section class="forecast-equation"><article><span>Current stock cost</span><strong><?=money($cost)?></strong><small>Money invested in remaining stock</small></article><div>→</div><article class="retail"><span>If all sold at retail</span><strong><?=money($retail)?></strong><small>Potential gross profit <?=money($retailProfit)?></small></article><div>or</div><article class="wholesale"><span>If all sold at wholesale</span><strong><?=money($wholesale)?></strong><small>Potential gross profit <?=money($wholesaleProfit)?></small></article></section>
<section class="kpi-grid"><article class="kpi"><span>Units available</span><strong><?=number_format($units,3)?></strong></article><article class="kpi"><span>Retail margin on stock</span><strong><?=$retail>0?number_format($retailProfit/$retail*100,2):'0.00'?>%</strong></article><article class="kpi"><span>Wholesale margin on stock</span><strong><?=$wholesale>0?number_format($wholesaleProfit/$wholesale*100,2):'0.00'?>%</strong></article><article class="kpi"><span>Income difference</span><strong><?=money($retail-$wholesale)?></strong><small>Retail forecast minus wholesale forecast</small></article></section>
<section class="panel table-panel forecast-table"><div class="panel-head"><div><span class="eyebrow">Product by product</span><h3><?=count($rows)?> stocked products</h3></div></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th class="right">Stock</th><th class="right">Buying cost</th><th class="right">Stock cost</th><th class="right">Retail income</th><th class="right">Retail profit</th><th class="right">Wholesale income</th><th class="right">Wholesale profit</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=e($r['item_code'])?></b><br><?=e($r['name'])?></td><td><?=e($r['category'])?></td><td class="right"><?=number_format($r['current_stock'],3).' '.e($r['unit'])?></td><td class="right"><?=money($r['avg_cost'])?></td><td class="right"><?=money($r['stock_cost'])?></td><td class="right"><?=money($r['retail_income'])?></td><td class="right profit"><?=money($r['retail_profit'])?></td><td class="right"><?=money($r['wholesale_income'])?></td><td class="right profit"><?=money($r['wholesale_profit'])?></td></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="2">TOTAL IF ALL STOCK IS SOLD</th><th class="right"><?=number_format($units,3)?></th><th></th><th class="right"><?=money($cost)?></th><th class="right"><?=money($retail)?></th><th class="right"><?=money($retailProfit)?></th><th class="right"><?=money($wholesale)?></th><th class="right"><?=money($wholesaleProfit)?></th></tr></tfoot></table></div></section>
<style>.forecast-head{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:20px}.forecast-head h2{margin:6px 0}.forecast-head p{margin:0;color:#6d7b73}.forecast-equation{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:12px;align-items:center;margin-bottom:20px}.forecast-equation article{padding:22px;border:1px solid #dfe5df;border-top:5px solid #3973b7;border-radius:14px;background:#fff}.forecast-equation article.retail{border-top-color:#249451}.forecast-equation article.wholesale{border-top-color:#8d62bb}.forecast-equation span,.forecast-equation small{display:block}.forecast-equation strong{display:block;margin:8px 0;font-size:28px}.forecast-equation small{color:#66756e}.forecast-table{margin-top:20px}.forecast-table table{min-width:1200px}.forecast-table .profit{color:#167744;font-weight:800}.forecast-table tfoot th{background:#eaf3e7}@media(max-width:850px){.forecast-head{align-items:stretch;flex-direction:column}.forecast-equation{grid-template-columns:1fr}.forecast-equation>div{text-align:center;transform:rotate(90deg)}}@media print{.sidebar,.topbar,.forecast-head .btn{display:none!important}.app{margin:0!important}.content{padding:0!important}.forecast-table .table-wrap{overflow:visible}.forecast-table table{min-width:0;font-size:9px}}</style><?php page_end();
