<?php
require __DIR__.'/bootstrap.php';require_auth();require __DIR__.'/partials.php';
$modules=[
'purchases'=>['Purchases','purchases.php','purchases.view','Supplier invoices, receiving and payables','SELECT p.purchase_no reference,p.purchase_date date,s.name party,p.payment_type type,p.status,p.total FROM purchases p JOIN suppliers s ON s.id=p.supplier_id ORDER BY p.id DESC LIMIT 30',['Invoice','Supplier','Type','Date','Status','Total']],
'inventory'=>['Inventory & serials','inventory.php','inventory.view','Stock position, serial tracking and movements','SELECT p.item_code reference,p.updated_at date,p.name party,COALESCE(c.name,"Uncategorised") type,IF(p.current_stock<=p.minimum_stock,"Low stock","Available") status,p.current_stock total FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.status="active" ORDER BY p.current_stock ASC LIMIT 50',['Code','Product','Category','Updated','Status','Quantity']],
'payments'=>['Customer payments','payments.php','payments.view','Receipts, allocations and customer balances','SELECT cp.receipt_no reference,cp.payment_date date,c.name party,cp.method type,"Received" status,cp.amount total FROM customer_payments cp JOIN customers c ON c.id=cp.customer_id ORDER BY cp.id DESC LIMIT 30',['Receipt','Customer','Method','Date','Status','Amount']],
'expenses'=>['Expenses & accounts','expenses.php','expenses.view','Operating costs, cash and bank transactions','SELECT e.expense_no reference,e.expense_date date,COALESCE(e.payee,ec.name) party,a.name type,"Posted" status,e.amount total FROM expenses e JOIN expense_categories ec ON ec.id=e.category_id JOIN accounts a ON a.id=e.account_id ORDER BY e.id DESC LIMIT 30',['Reference','Payee','Account','Date','Status','Amount']],
'reports'=>['Reports & CFO','reports.php','reports.view','Profitability, credit, stock value and management reporting','SELECT s.sale_no reference,s.sale_date date,COALESCE(c.name,"Walk-in") party,CONCAT(s.sale_type," / ",s.payment_type) type,s.status,s.total FROM sales s LEFT JOIN customers c ON c.id=s.customer_id ORDER BY s.id DESC LIMIT 50',['Invoice','Customer','Channel','Date','Status','Revenue']],
'users'=>['Users & audit','users.php','users.manage','Access control, sessions and accountability','SELECT CONCAT("AUD-",a.id) reference,a.created_at date,a.actor_name party,CONCAT(a.action_type," · ",a.entity_type) type,"Recorded" status,COALESCE(a.entity_id,0) total FROM audit_logs a ORDER BY a.id DESC LIMIT 50',['Audit ID','Actor','Action','Date','Status','Entity ID']],
'settings'=>['System settings','settings.php','settings.manage','Business rules, backups and configuration','SELECT setting_key reference,updated_at date,setting_value party,"Configuration" type,"Active" status,0 total FROM settings ORDER BY setting_key',['Key','Value','Type','Updated','Status','—']]
];
$m=$modules[$module]??null;if(!$m){http_response_code(404);exit('Unknown module');}[$title,$active,$permission,$subtitle,$sql,$heads]=$m;if(!can($permission)){http_response_code(403);exit('Forbidden');}$rows=$db->query($sql)->fetchAll();
$metrics=[];if($module==='reports'){$metrics=[['Gross sales',$db->query("SELECT COALESCE(SUM(total),0) FROM sales WHERE status NOT IN ('cancelled','returned')")->fetchColumn()],['Gross profit',$db->query("SELECT COALESCE(SUM(gross_profit),0) FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.status NOT IN ('cancelled','returned')")->fetchColumn()],['Operating expenses',$db->query('SELECT COALESCE(SUM(amount),0) FROM expenses')->fetchColumn()],['Potential retail profit',$db->query('SELECT COALESCE(SUM(current_stock*(retail_price-avg_cost)),0) FROM products')->fetchColumn()]];}
page_start($title,$active);?>
<section class="hero"><div><span class="eyebrow">ERP workspace</span><h2><?=e($title)?></h2><p><?=e($subtitle)?></p></div><div class="hero-meta"><span>Records shown</span><b><?=count($rows)?></b></div></section><?php if($metrics):?><section class="kpi-grid"><?php foreach($metrics as [$label,$value]):?><article class="kpi"><div class="kpi-top"><span><?=e($label)?></span><i>↗</i></div><strong><?=money($value)?></strong><small>Posted transactions only</small></article><?php endforeach;?></section><?php endif;?><section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">Detailed records</span><h3><?=e($title)?> register</h3></div><div><button class="btn secondary" onclick="window.print()">Print</button></div></div><div class="table-wrap"><table><thead><tr><?php foreach($heads as $h):?><th><?=e($h)?></th><?php endforeach;?></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6"><div class="empty-state compact"><b>No records yet</b><span>This register will fill as operational transactions are posted.</span></div></td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td><b><?=e($r['reference'])?></b></td><td><?=e($r['party'])?></td><td><span class="tag"><?=e(str_replace('_',' ',$r['type']))?></span></td><td><?=date('d M Y',strtotime($r['date']))?></td><td><span class="status active"><?=e($r['status'])?></span></td><td class="right"><b><?=$module==='settings'?e($r['total']):($module==='inventory'?e($r['total']):money($r['total']))?></b></td></tr><?php endforeach;?></tbody></table></div></section><?php page_end();

