<?php
require __DIR__.'/bootstrap.php';
require_auth();
if (!can('products.view')) { http_response_code(403); exit('Forbidden'); }
$id=(int)($_GET['id']??0);
$stmt=$db->prepare('SELECT p.*,c.name category,b.name brand FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN brands b ON b.id=p.brand_id WHERE p.id=?');
$stmt->execute([$id]);$product=$stmt->fetch();
if(!$product){http_response_code(404);exit('Product not found');}
$stmt=$db->prepare('SELECT s.id,s.sale_no,s.sale_date,s.sale_type,s.payment_type,s.status,s.total invoice_total,s.paid_amount invoice_paid,s.balance invoice_balance,COALESCE(c.name,"Walk-in Customer") customer,si.quantity,si.unit_price,si.discount,si.line_total,si.historical_unit_cost,si.gross_profit FROM sale_items si JOIN sales s ON s.id=si.sale_id LEFT JOIN customers c ON c.id=s.customer_id WHERE si.product_id=? AND s.status NOT IN("cancelled","returned") ORDER BY s.sale_date DESC,s.id DESC');
$stmt->execute([$id]);$sales=$stmt->fetchAll();
$summary=['qty'=>0,'value'=>0,'cost'=>0,'profit'=>0,'cash'=>0,'credit'=>0,'collected'=>0,'due'=>0];
foreach($sales as $row){$line=(float)$row['line_total'];$ratio=(float)$row['invoice_total']>0?$line/(float)$row['invoice_total']:0;$summary['qty']+=(float)$row['quantity'];$summary['value']+=$line;$summary['cost']+=(float)$row['historical_unit_cost']*(float)$row['quantity'];$summary['profit']+=(float)$row['gross_profit'];$summary[$row['payment_type']==='cash'?'cash':'credit']+=$line;$summary['collected']+=(float)$row['invoice_paid']*$ratio;if($row['payment_type']==='credit')$summary['due']+=(float)$row['invoice_balance']*$ratio;}
$margin=$summary['value']>0?$summary['profit']/$summary['value']*100:0;$stockCost=(float)$product['current_stock']*(float)$product['avg_cost'];
page_start('Product Report - '.$product['item_code'],'products.php');
?>
<div class="report-actions"><a class="btn secondary" href="products.php">← Products</a><button class="btn primary" onclick="window.print()">Print / Save PDF</button></div>
<section class="panel product-print-report">
 <header class="report-brand"><div><img src="assets/supun-traders-logo.png" alt="Supun Traders"><p>114, Second Cross Street, Pettah, Colombo 11</p></div><div class="right"><span class="eyebrow">Full Product Report</span><h2><?=e($product['item_code'])?></h2><p>Printed <?=date('d F Y, h:i A')?></p></div></header>
 <div class="report-title"><h1><?=e($product['name'])?></h1><p><?=e($product['category']?:'Uncategorized')?> · <?=e($product['brand']?:'No brand')?> · <?=e($product['model']?:'No model')?></p></div>
 <div class="report-kpis"><article><span>Current Stock</span><strong><?=e($product['current_stock'].' '.$product['unit'])?></strong></article><article><span>Buying Cost Each</span><strong><?=money($product['avg_cost'])?></strong></article><article><span>Stock at Cost</span><strong><?=money($stockCost)?></strong></article><article><span>Sold Quantity</span><strong><?=number_format($summary['qty'],3).' '.e($product['unit'])?></strong></article><article><span>All Sold Value</span><strong><?=money($summary['value'])?></strong></article><article><span>Realized Profit</span><strong><?=money($summary['profit'])?></strong><small>Margin <?=number_format($margin,2)?>%</small></article><article class="collected"><span>Money Collected</span><strong><?=money($summary['collected'])?></strong></article><article><span>Cash Sales</span><strong><?=money($summary['cash'])?></strong></article><article class="credit"><span>Credit Sales</span><strong><?=money($summary['credit'])?></strong></article><article class="due"><span>Credit Still to Collect</span><strong><?=money($summary['due'])?></strong></article></div>
 <div class="price-comparison"><article><h3>Retail Price</h3><strong><?=money($product['retail_price'])?></strong><p>Profit each <?=money((float)$product['retail_price']-(float)$product['avg_cost'])?></p><p>Margin <?=number_format((float)$product['retail_price']>0?(((float)$product['retail_price']-(float)$product['avg_cost'])/(float)$product['retail_price'])*100:0,2)?>%</p></article><article><h3>Wholesale Price</h3><strong><?=money($product['wholesale_price'])?></strong><p>Profit each <?=money((float)$product['wholesale_price']-(float)$product['avg_cost'])?></p><p>Margin <?=number_format((float)$product['wholesale_price']>0?(((float)$product['wholesale_price']-(float)$product['avg_cost'])/(float)$product['wholesale_price'])*100:0,2)?>%</p></article></div>
 <section class="report-sales"><span class="eyebrow">Invoice history</span><h2>Every sale of this product</h2><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Sale</th><th>Payment</th><th class="right">Qty</th><th class="right">Unit Price</th><th class="right">Sold Value</th><th class="right">Saved Cost</th><th class="right">Profit</th><th>Status</th></tr></thead><tbody><?php if(!$sales):?><tr><td colspan="11">No sales recorded for this product.</td></tr><?php endif;?><?php foreach($sales as $row):?><tr><td><a href="sale_view.php?id=<?=$row['id']?>"><b><?=e($row['sale_no'])?></b></a></td><td><?=date('d M Y',strtotime($row['sale_date']))?></td><td><?=e($row['customer'])?></td><td><?=e(ucfirst($row['sale_type']))?></td><td><span class="report-label <?=$row['payment_type']==='cash'?'cash':'credit'?>"><?=e(ucfirst($row['payment_type']))?></span></td><td class="right"><?=e($row['quantity'])?></td><td class="right"><?=money($row['unit_price'])?></td><td class="right"><?=money($row['line_total'])?></td><td class="right"><?=money((float)$row['historical_unit_cost']*(float)$row['quantity'])?></td><td class="right"><b><?=money($row['gross_profit'])?></b></td><td><?=e(ucwords(str_replace('_',' ',$row['status'])))?></td></tr><?php endforeach;?></tbody></table></div></section>
</section>
<style>
.report-actions{display:flex;justify-content:space-between;margin-bottom:16px}.product-print-report{padding:28px}.report-brand{display:flex;justify-content:space-between;border-bottom:2px solid #17583f;padding-bottom:18px}.report-brand img{width:190px;max-height:70px;object-fit:contain;object-position:left}.report-brand p,.report-title p{color:#718078}.report-title{margin:22px 0}.report-title h1{margin:0}.report-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.report-kpis article,.price-comparison article{padding:14px;border:1px solid #dfe5df;border-radius:11px;background:#f8faf7;display:flex;flex-direction:column;gap:6px}.report-kpis span{font-size:10px;text-transform:uppercase;color:#718078}.report-kpis strong{font-size:17px}.report-kpis small{color:#718078}.report-kpis .collected{background:#e7f5eb}.report-kpis .credit{background:#fff5df}.report-kpis .due{background:#fff0ee}.report-kpis .due strong{color:#c83b32}.price-comparison{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0}.price-comparison h3,.price-comparison p{margin:0}.price-comparison strong{font-size:22px}.report-sales{margin-top:24px}.report-label{padding:5px 9px;border-radius:20px;font-weight:800;font-size:11px}.report-label.cash{background:#dcf1e2;color:#14723e}.report-label.credit{background:#ffedc9;color:#9a5a05}@media(max-width:900px){.report-kpis{grid-template-columns:repeat(2,1fr)}}@media print{.sidebar,.topbar,.report-actions{display:none!important}.app{margin:0!important;width:100%!important}.content{padding:0!important}.product-print-report{border:0!important;box-shadow:none!important;padding:0}.report-kpis{grid-template-columns:repeat(5,1fr)}.table-wrap{overflow:visible!important}table{font-size:9px}a{color:inherit;text-decoration:none}}
</style>
<?php page_end();
