<?php
require __DIR__.'/bootstrap.php';require_auth();if(!can('reports.view')){http_response_code(403);exit('Forbidden');}require __DIR__.'/partials.php';
$type=$_GET['type']??'sales';$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-d');$cards=['sales'=>['How much did we sell?','All paid and credit sales for the selected dates.'],'credit'=>['Who owes us money?','Unpaid and partly paid customer invoices.'],'stock'=>['What stock do we have?','Quantity and current value of products.'],'profit'=>['How much profit did we make?','Sales revenue minus saved historical product cost.'],'purchases'=>['What did we buy?','Supplier purchases and amounts still payable.']];if(!isset($cards[$type]))$type='sales';$rows=[];$summary=0;
if($type==='sales'){$s=$db->prepare('SELECT s.sale_no reference,s.sale_date date,COALESCE(c.name,"Walk-in") party,CONCAT(s.sale_type," / ",s.payment_type) detail,s.status,s.total amount FROM sales s LEFT JOIN customers c ON c.id=s.customer_id WHERE DATE(s.sale_date) BETWEEN ? AND ? AND s.status NOT IN("cancelled","returned") ORDER BY s.sale_date DESC');$s->execute([$from,$to]);$rows=$s->fetchAll();}
elseif($type==='credit'){$rows=$db->query('SELECT sale_no reference,sale_date date,COALESCE(c.name,"Unknown") party,CONCAT("Due ",COALESCE(DATE_FORMAT(due_date,"%d %b %Y"),"not set")) detail,s.status,s.balance amount FROM sales s LEFT JOIN customers c ON c.id=s.customer_id WHERE s.balance>0 AND s.status IN("unpaid","partially_paid","overdue") ORDER BY due_date')->fetchAll();}
elseif($type==='stock'){$rows=$db->query('SELECT item_code reference,updated_at date,name party,CONCAT(current_stock," ",unit," @ cost") detail,IF(current_stock<=minimum_stock,"Low stock","Available") status,current_stock*avg_cost amount FROM products WHERE status="active" ORDER BY name')->fetchAll();}
elseif($type==='profit'){$s=$db->prepare('SELECT s.sale_no reference,s.sale_date date,COALESCE(c.name,"Walk-in") party,CONCAT("Revenue ",FORMAT(s.total,2)) detail,s.status,SUM(si.gross_profit) amount FROM sales s JOIN sale_items si ON si.sale_id=s.id LEFT JOIN customers c ON c.id=s.customer_id WHERE DATE(s.sale_date) BETWEEN ? AND ? AND s.status NOT IN("cancelled","returned") GROUP BY s.id ORDER BY s.sale_date DESC');$s->execute([$from,$to]);$rows=$s->fetchAll();}
else{$s=$db->prepare('SELECT p.purchase_no reference,p.purchase_date date,s.name party,CONCAT("Supplier invoice ",p.supplier_invoice) detail,p.status,p.total amount FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.purchase_date BETWEEN ? AND ? ORDER BY p.purchase_date DESC');$s->execute([$from,$to]);$rows=$s->fetchAll();}$summary=array_sum(array_map(fn($r)=>(float)$r['amount'],$rows));page_start('Reports','reports.php');?>
<section class="report-chooser"><span class="eyebrow">Choose one question</span><h2>What do you want to know?</h2><div><?php foreach($cards as $key=>[$label,$desc]):?><a href="?type=<?=$key?>&from=<?=e($from)?>&to=<?=e($to)?>" class="<?=$type===$key?'active':''?>"><b><?=e($label)?></b><span><?=e($desc)?></span></a><?php endforeach;?></div></section><section class="panel"><form class="report-filter"><input type="hidden" name="type" value="<?=e($type)?>"><label>From<input type="date" name="from" value="<?=e($from)?>"></label><label>To<input type="date" name="to" value="<?=e($to)?>"></label><button class="btn primary">Show Report</button><button type="button" class="btn secondary" onclick="window.print()">Print</button></form></section><section class="kpi-grid one"><article class="kpi"><div class="kpi-top"><span><?=e($cards[$type][0])?></span><i>✓</i></div><strong><?=money($summary)?></strong><small><?=count($rows)?> record(s) shown</small></article></section><section class="panel table-panel"><div class="panel-head"><div><span class="eyebrow">Detailed list</span><h3><?=e($cards[$type][1])?></h3></div></div><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Name</th><th>Details</th><th>Date</th><th>Status</th><th class="right">Amount</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6"><div class="empty-state compact"><b>No records for this selection</b><span>Try a different date range.</span></div></td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td><b><?=e($r['reference'])?></b></td><td><?=e($r['party'])?></td><td><?=e(str_replace('_',' ',$r['detail']))?></td><td><?=date('d M Y',strtotime($r['date']))?></td><td><span class="status active"><?=e(str_replace('_',' ',$r['status']))?></span></td><td class="right"><b><?=money($r['amount'])?></b></td></tr><?php endforeach;?></tbody></table></div></section><?php page_end();
