<?php
session_start();
include '../db.php';
require_once '../includes/advance_accounts.php';
if (!isset($_SESSION['user_id']) || !in_array($_SESSION['role'] ?? '', ['admin','accountant'], true)) { header('Location: ../login.php'); exit; }
ensureAdvancePaymentSchema($conn);

$from=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['from']??'')?$_GET['from']:date('Y-m-01');
$to=preg_match('/^\d{4}-\d{2}-\d{2}$/',$_GET['to']??'')?$_GET['to']:date('Y-m-d');
$type=in_array($_GET['type']??'all',['all','credit','installment'],true)?$_GET['type']:'all';
$method=trim($_GET['method']??'');$customer=trim($_GET['customer']??'');
$from_sql=$conn->real_escape_string($from);$to_sql=$conn->real_escape_string($to);$method_sql=$conn->real_escape_string($method);$customer_sql=$conn->real_escape_string($customer);
$filters=["DATE(t.created_at) BETWEEN '$from_sql' AND '$to_sql'","t.transaction_type='deposit'"];
if($type==='credit')$filters[]='t.order_id IS NULL';elseif($type==='installment')$filters[]='t.order_id IS NOT NULL';
if($method!=='')$filters[]="t.payment_method='$method_sql'";
if($customer!=='')$filters[]="(c.customer_name LIKE '%$customer_sql%' OR c.account_number LIKE '%$customer_sql%' OR c.phone LIKE '%$customer_sql%')";
$where=implode(' AND ',$filters);

$rows=[];$result=$conn->query("SELECT t.transaction_id,t.created_at,t.receipt_number,t.order_id,t.amount,t.remaining_amount,t.payment_method,t.reference_note,t.settlement_status,c.account_number,c.customer_name,c.phone,o.order_number,o.order_status,u.full_name received_by FROM advance_payment_transactions t JOIN customer_accounts c ON c.customer_id=t.customer_id LEFT JOIN orders o ON o.order_id=t.order_id LEFT JOIN users u ON u.user_id=t.created_by WHERE $where ORDER BY t.created_at DESC,t.transaction_id DESC");
while($result&&$row=$result->fetch_assoc())$rows[]=$row;
$credit_received=0;$installment_received=0;foreach($rows as $row){if($row['order_id']===null)$credit_received+=(float)$row['amount'];else$installment_received+=(float)$row['amount'];}
$credit_used=(float)($conn->query("SELECT COALESCE(SUM(u.amount),0) total FROM advance_payment_transactions u JOIN advance_payment_transactions d ON d.transaction_id=u.parent_transaction_id WHERE u.transaction_type='sale_usage' AND d.order_id IS NULL AND DATE(u.created_at) BETWEEN '$from_sql' AND '$to_sql'")->fetch_assoc()['total']??0);
$liability=(float)($conn->query("SELECT COALESCE(SUM(remaining_amount),0) total FROM advance_payment_transactions WHERE transaction_type='deposit' AND order_id IS NULL AND remaining_amount>0")->fetch_assoc()['total']??0);
$open=(array)$conn->query("SELECT COUNT(DISTINCT o.order_id) orders,COALESCE(SUM(GREATEST(0,(CASE WHEN o.total_amount>0 THEN o.total_amount ELSE (SELECT COALESCE(SUM(oi.line_total),0) FROM order_items oi WHERE oi.order_id=o.order_id) END)-(SELECT COALESCE(SUM(d.remaining_amount),0) FROM advance_payment_transactions d WHERE d.order_id=o.order_id AND d.transaction_type='deposit'))),0) outstanding FROM orders o WHERE o.order_status='open' AND EXISTS(SELECT 1 FROM advance_payment_transactions x WHERE x.order_id=o.order_id AND x.transaction_type='deposit')")->fetch_assoc();

if(($_GET['export']??'')==='csv'){
    header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="payment-report-'.$from.'-to-'.$to.'.csv"');$out=fopen('php://output','w');fputcsv($out,['Type','Date','Receipt','Account','Customer','Order','Method','Amount','Remaining','Status','Purpose','Received By']);foreach($rows as $row)fputcsv($out,[$row['order_id']===null?'Account Credit':'Order Installment',$row['created_at'],$row['receipt_number'],$row['account_number'],$row['customer_name'],$row['order_number']?:'-',$row['payment_method'],$row['amount'],$row['order_id']===null?$row['remaining_amount']:max(0,(float)$row['amount']-(float)$row['remaining_amount']),$row['order_status']?:$row['settlement_status'],$row['reference_note'],$row['received_by']]);fclose($out);exit;
}
$methods=['Cash','Card','QR','Bank Transfer','Cheque'];
function reportMoney($value){return 'Rs. '.number_format((float)$value,2);}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Credit & Installment Report</title><style><?php include 'shared_style.php'; ?>
.report{padding:22px}.filters,.panel,.kpi{background:#fff;border:1px solid var(--border);border-radius:12px}.filters{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr)) auto;gap:10px;padding:14px;margin-bottom:14px}.filters label{font-size:10px;font-weight:900;color:var(--text-muted);text-transform:uppercase}.filters input,.filters select{width:100%;height:38px;border:1px solid var(--border);border-radius:7px;padding:0 9px}.filter-actions{display:flex;gap:7px;align-items:end}.report-btn{height:38px;border:0;border-radius:7px;padding:0 13px;background:var(--primary);color:#fff;font-weight:900;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:6px;white-space:nowrap}.report-btn.orange{background:#e85d04}.report-btn.gray{background:#475467}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.kpi{padding:14px}.kpi span{font-size:10px;text-transform:uppercase;color:var(--text-muted);font-weight:900}.kpi strong{display:block;font-size:19px;margin-top:5px;color:var(--primary)}.panel{padding:15px}.panel-head{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:10px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px;min-width:1100px}th{background:#f8fafc;color:#667085;text-align:left;padding:9px}td{padding:10px 9px;border-bottom:1px solid #eaecf0;vertical-align:top}.chip{padding:4px 8px;border-radius:20px;font-size:10px;font-weight:900}.credit{background:#ecfdf3;color:#027a48}.installment{background:#fff7ed;color:#c2410c}.money{font-weight:900}.empty{text-align:center;color:#667085;padding:30px}@media(max-width:1100px){.filters{grid-template-columns:repeat(2,1fr)}.kpis{grid-template-columns:repeat(2,1fr)}}@media print{.sidebar,.topbar,.filters,.no-print{display:none!important}.main{margin-left:0!important}.report{padding:0}.panel,.kpi{box-shadow:none}.table-wrap{overflow:visible}table{min-width:0;font-size:9px}@page{size:A4 landscape;margin:8mm}}
</style></head><body><?php include 'shared_nav.php'; ?><main class="main"><?php include 'shared_topbar.php'; ?><div class="report">
<form class="filters"><div><label>From</label><input type="date" name="from" value="<?php echo htmlspecialchars($from); ?>"></div><div><label>To</label><input type="date" name="to" value="<?php echo htmlspecialchars($to); ?>"></div><div><label>Report Type</label><select name="type"><option value="all">All Payments</option><option value="credit" <?php echo $type==='credit'?'selected':''; ?>>Account Credit</option><option value="installment" <?php echo $type==='installment'?'selected':''; ?>>Installments</option></select></div><div><label>Payment Method</label><select name="method"><option value="">All Methods</option><?php foreach($methods as $item): ?><option <?php echo $method===$item?'selected':''; ?>><?php echo $item; ?></option><?php endforeach; ?></select></div><div><label>Customer</label><input name="customer" value="<?php echo htmlspecialchars($customer); ?>" placeholder="Name, account or phone"></div><div class="filter-actions"><button class="report-btn">Apply</button><a class="report-btn gray" href="payment_reports.php">Reset</a></div></form>
<section class="kpis"><div class="kpi"><span>Account Credit Received</span><strong><?php echo reportMoney($credit_received); ?></strong></div><div class="kpi"><span>Account Credit Used</span><strong><?php echo reportMoney($credit_used); ?></strong></div><div class="kpi"><span>Current Credit Liability</span><strong><?php echo reportMoney($liability); ?></strong></div><div class="kpi"><span>Installments Received</span><strong><?php echo reportMoney($installment_received); ?></strong></div><div class="kpi"><span>Open Installment Balance</span><strong><?php echo reportMoney($open['outstanding']??0); ?></strong><small><?php echo (int)($open['orders']??0); ?> orders</small></div></section>
<section class="panel"><div class="panel-head"><div><h2 style="margin:0">Account Credit & Installment Transactions</h2><small><?php echo htmlspecialchars($from); ?> to <?php echo htmlspecialchars($to); ?> · <?php echo count($rows); ?> records</small></div><div class="no-print" style="display:flex;gap:7px"><a class="report-btn orange" href="?<?php echo htmlspecialchars(http_build_query(array_merge($_GET,['export'=>'csv']))); ?>"><i class="fa-solid fa-file-csv"></i> Export CSV</a><button class="report-btn gray" onclick="window.print()"><i class="fa-solid fa-print"></i> Print</button></div></div><div class="table-wrap"><table><thead><tr><th>Type</th><th>Date</th><th>Receipt</th><th>Customer</th><th>Order</th><th>Method</th><th>Received</th><th>Available / Status</th><th>Purpose</th><th>Received By</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="10" class="empty">No payments found for these filters.</td></tr><?php else: foreach($rows as $row): $isCredit=$row['order_id']===null; ?><tr><td><span class="chip <?php echo $isCredit?'credit':'installment'; ?>"><?php echo $isCredit?'Account Credit':'Installment'; ?></span></td><td><?php echo date('d M Y H:i',strtotime($row['created_at'])); ?></td><td><strong><?php echo htmlspecialchars($row['receipt_number']); ?></strong></td><td><strong><?php echo htmlspecialchars($row['customer_name']); ?></strong><br><small><?php echo htmlspecialchars($row['account_number'].' · '.($row['phone']?:'-')); ?></small></td><td><?php echo htmlspecialchars($row['order_number']?:'-'); ?></td><td><?php echo htmlspecialchars($row['payment_method']); ?></td><td class="money"><?php echo reportMoney($row['amount']); ?></td><td><?php echo $isCredit?reportMoney($row['remaining_amount']):htmlspecialchars(ucfirst($row['order_status']?:$row['settlement_status'])); ?></td><td><?php echo htmlspecialchars($row['reference_note']?:'-'); ?></td><td><?php echo htmlspecialchars($row['received_by']?:'-'); ?></td></tr><?php endforeach; endif; ?></tbody></table></div></section>
</div></main></body></html>
