<?php
include '../includes/auth.php';include '../db.php';include 'purchase_helpers.php';include 'quick_supplier.php';
if(isset($_GET['template'])){header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="supun_purchase_import_template.csv"');$out=fopen('php://output','w');fputcsv($out,['SKU','Quantity','Unit Cost']);fputcsv($out,['REF-240L-001','10','142000.00']);fputcsv($out,['FAN-CEIL-056','25','14500.00']);fclose($out);exit;}
$msg='';$msgType='';$preview=$_SESSION['purchase_import_preview']??[];$quickSupplier=handleQuickSupplier($conn);$newSupplierId=(int)$quickSupplier['id'];if($quickSupplier['handled']){$msg=$quickSupplier['message'];$msgType=$quickSupplier['type'];}
if(isset($_POST['clear_preview'])){unset($_SESSION['purchase_import_preview']);$preview=[];}
if(isset($_POST['preview_import'])){
    $preview=[];$errors=[];
    if(!isset($_FILES['purchase_file'])||$_FILES['purchase_file']['error']!==UPLOAD_ERR_OK){$errors[]='Select a CSV file.';}
    elseif($_FILES['purchase_file']['size']>2*1024*1024){$errors[]='The file must be smaller than 2 MB.';}
    elseif(strtolower(pathinfo($_FILES['purchase_file']['name'],PATHINFO_EXTENSION))!=='csv'){$errors[]='Use the downloadable CSV template. It can be edited with Microsoft Excel.';}
    else{$fh=fopen($_FILES['purchase_file']['tmp_name'],'r');$header=fgetcsv($fh);$expected=['sku','quantity','unit cost'];$normal=array_map(fn($v)=>strtolower(trim((string)$v)),$header?:[]);if($normal!==$expected){$errors[]='Invalid columns. Required: SKU, Quantity, Unit Cost.';}else{$line=1;$lookup=$conn->prepare("SELECT product_id,product_name,sku,stock_qty,unit,cost_price FROM products WHERE sku=? AND status=1 LIMIT 1");while(($row=fgetcsv($fh))!==false){$line++;if(count($row)<3||trim(implode('',$row))==='')continue;$sku=trim($row[0]);$qty=(float)$row[1];$cost=(float)$row[2];$lookup->bind_param('s',$sku);$lookup->execute();$product=$lookup->get_result()->fetch_assoc();$rowErrors=[];if(!$product)$rowErrors[]='Unknown or inactive SKU';if($qty<=0)$rowErrors[]='Quantity must be greater than zero';if($cost<0)$rowErrors[]='Unit cost cannot be negative';$preview[]=['line'=>$line,'sku'=>$sku,'quantity'=>$qty,'unit_cost'=>$cost,'product'=>$product,'errors'=>$rowErrors];} $lookup->close();if(!$preview)$errors[]='The spreadsheet has no product rows.';}fclose($fh);}
    if($errors){$msg=implode(' ',$errors);$msgType='error';unset($_SESSION['purchase_import_preview']);$preview=[];}else{$_SESSION['purchase_import_preview']=$preview;$msg='Spreadsheet read successfully. Review every row before creating the purchase.';$msgType='success';}
}
if(isset($_POST['confirm_import'])){
    $preview=$_SESSION['purchase_import_preview']??[];$supplierId=(int)($_POST['supplier_id']??0);$invoice=trim($_POST['supplier_invoice']??'');$date=$_POST['purchase_date']??date('Y-m-d');$notes=trim($_POST['notes']??'Imported from purchase spreadsheet');$hasErrors=false;foreach($preview as $r)if($r['errors'])$hasErrors=true;
    if(!$preview||$supplierId<=0||$hasErrors){$msg='Select a supplier and correct all spreadsheet errors first.';$msgType='error';}
    else{$conn->begin_transaction();try{$subtotal=0;foreach($preview as $r)$subtotal+=(float)$r['quantity']*(float)$r['unit_cost'];$uid=(int)$_SESSION['user_id'];$s=$conn->prepare("INSERT INTO purchases (supplier_id,supplier_invoice,purchase_date,subtotal,total_amount,notes,created_by) VALUES (?,NULLIF(?,''),?,?,?,?,?)");$s->bind_param('issddsi',$supplierId,$invoice,$date,$subtotal,$subtotal,$notes,$uid);$s->execute();$purchaseId=$conn->insert_id;$s->close();$number=purchaseNumber($purchaseId);$u=$conn->prepare("UPDATE purchases SET purchase_number=? WHERE purchase_id=?");$u->bind_param('si',$number,$purchaseId);$u->execute();$u->close();$item=$conn->prepare("INSERT INTO purchase_items (purchase_id,product_id,quantity,unit_cost,line_total) VALUES (?,?,?,?,?)");foreach($preview as $r){$pid=(int)$r['product']['product_id'];$q=(float)$r['quantity'];$c=(float)$r['unit_cost'];$lt=$q*$c;$item->bind_param('iiddd',$purchaseId,$pid,$q,$c,$lt);$item->execute();}$item->close();$conn->commit();unset($_SESSION['purchase_import_preview']);header('Location:purchase_view.php?id='.$purchaseId.'&imported=1');exit;}catch(Throwable $e){$conn->rollback();$msg=$e->getMessage();$msgType='error';}}
}
$suppliers=$conn->query("SELECT supplier_id,supplier_name FROM suppliers WHERE status=1 ORDER BY supplier_name");$validRows=0;$importTotal=0;$errorRows=0;foreach($preview as $r){if($r['errors'])$errorRows++;else{$validRows++;$importTotal+=(float)$r['quantity']*(float)$r['unit_cost'];}}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Purchase Spreadsheet Import</title><link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Lora:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><style><?php include 'shared_style.php';include 'erp_style.php';?>.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:18px}.step{padding:15px;background:#fff;border:1.5px solid var(--border);border-radius:var(--radius);display:flex;gap:10px}.step-num{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:var(--primary);color:#fff;font-weight:900;flex:none}.upload-zone{padding:30px;text-align:center;border:2px dashed var(--border-dk);border-radius:10px;background:#fafcfd}.upload-zone i{font-size:34px;color:var(--green);margin-bottom:10px}.import-error{color:var(--red);font-size:10px;font-weight:900}.import-ok{color:var(--green);font-size:11px;font-weight:900}@media(max-width:750px){.steps{grid-template-columns:1fr}}</style></head><body>
<?php include 'shared_nav.php';?><main class="main"><?php include 'shared_topbar.php';?><div class="content"><div class="page-header"><div><h1 class="page-title-h"><i class="fa-solid fa-file-excel"></i> Purchase Spreadsheet Import</h1><p class="page-sub">Create a bulk purchase from an Excel-compatible CSV template</p></div><div class="quick-links"><a class="btn-secondary" href="purchases.php"><i class="fa-solid fa-arrow-left"></i> Purchases</a><a class="btn-primary" href="?template=1"><i class="fa-solid fa-download"></i> Download Template</a></div></div>
<?php if($msg):?><div class="alert <?php echo $msgType;?>"><?php echo htmlspecialchars($msg);?></div><?php endif;?>
<?php renderQuickSupplierForm(); ?>
<?php if($newSupplierId):?><script>document.addEventListener('DOMContentLoaded',()=>{const s=document.querySelector('select[name="supplier_id"]');if(s)s.value='<?php echo $newSupplierId;?>';});</script><?php endif;?>
<div class="steps"><div class="step"><span class="step-num">1</span><div><strong>Download Template</strong><p class="muted">Open the CSV in Excel. Keep the three column names unchanged.</p></div></div><div class="step"><span class="step-num">2</span><div><strong>Enter Products</strong><p class="muted">Use product SKU, quantity and supplier unit cost.</p></div></div><div class="step"><span class="step-num">3</span><div><strong>Preview & Confirm</strong><p class="muted">Nothing changes stock until the purchase is reviewed and received.</p></div></div></div>
<?php if(!$preview):?><section class="card"><div class="card-head"><h4><i class="fa-solid fa-cloud-arrow-up"></i> Upload Completed Template</h4></div><form method="post" enctype="multipart/form-data" class="erp-form"><div class="upload-zone"><i class="fa-solid fa-file-csv"></i><h3>Select your purchase CSV</h3><p class="muted" style="margin:6px 0 15px">Maximum 2 MB. Save the Excel workbook as CSV UTF-8 before uploading.</p><input class="inp" type="file" name="purchase_file" accept=".csv,text/csv" required></div><button class="btn-primary" name="preview_import" style="margin-top:14px"><i class="fa-solid fa-magnifying-glass"></i> Validate & Preview</button></form></section><?php else:?>
<div class="erp-stats"><div class="erp-stat green"><span>Valid Rows</span><strong><?php echo $validRows;?></strong></div><div class="erp-stat <?php echo $errorRows?'amber':'green';?>"><span>Rows With Errors</span><strong><?php echo $errorRows;?></strong></div><div class="erp-stat"><span>Products / Units</span><strong><?php echo number_format(array_sum(array_column($preview,'quantity')),0);?></strong></div><div class="erp-stat"><span>Import Total</span><strong>Rs. <?php echo number_format($importTotal,2);?></strong></div></div>
<section class="card table-card-full"><div class="card-head"><h4><i class="fa-solid fa-table-list"></i> Import Preview</h4><form method="post"><button class="btn-small" name="clear_preview"><i class="fa-solid fa-rotate-left"></i> Upload Another</button></form></div><div class="tbl-wrap"><table><thead><tr><th>Line</th><th>SKU</th><th>Matched Product</th><th>Current Stock</th><th>Quantity</th><th>Unit Cost</th><th>Line Total</th><th>Validation</th></tr></thead><tbody><?php foreach($preview as $r):?><tr><td><?php echo (int)$r['line'];?></td><td><strong><?php echo htmlspecialchars($r['sku']);?></strong></td><td><?php echo htmlspecialchars($r['product']['product_name']??'Not found');?></td><td><?php echo isset($r['product'])?number_format((float)$r['product']['stock_qty'],0).' '.htmlspecialchars($r['product']['unit']):'-';?></td><td><?php echo number_format((float)$r['quantity'],3);?></td><td class="money">Rs. <?php echo number_format((float)$r['unit_cost'],2);?></td><td class="money">Rs. <?php echo number_format((float)$r['quantity']*(float)$r['unit_cost'],2);?></td><td><?php if($r['errors']):?><span class="import-error"><?php echo htmlspecialchars(implode(', ',$r['errors']));?></span><?php else:?><span class="import-ok"><i class="fa-solid fa-circle-check"></i> Valid</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card" style="margin-top:18px"><div class="card-head"><h4><i class="fa-solid fa-file-circle-check"></i> Create Draft Purchase</h4></div><form method="post" class="erp-form"><div class="form-grid"><div class="field"><label>Supplier *</label><select class="inp" name="supplier_id" required><option value="">Select supplier</option><?php while($s=$suppliers->fetch_assoc()):?><option value="<?php echo (int)$s['supplier_id'];?>"><?php echo htmlspecialchars($s['supplier_name']);?></option><?php endwhile;?></select></div><div class="field"><label>Purchase Date</label><input class="inp" type="date" name="purchase_date" value="<?php echo date('Y-m-d');?>" required></div><div class="field"><label>Supplier Invoice</label><input class="inp" name="supplier_invoice"></div><div class="field"><label>Internal Note</label><input class="inp" name="notes" value="Imported from purchase spreadsheet"></div></div><p class="muted" style="margin-top:12px">This creates a draft. Open it from the purchase register and click Receive All Stock after checking the physical delivery.</p><button class="btn-primary" name="confirm_import" style="margin-top:12px" <?php echo $errorRows?'disabled title="Correct spreadsheet errors first"':'';?>><i class="fa-solid fa-file-import"></i> Create Draft Purchase</button></form></section><?php endif;?>
</div></main></body></html>
