<?php
include '../includes/auth.php';
include '../db.php';
header('Location: product_import.php');
exit;
$msg=''; $msgType='';

if (isset($_POST['save_supplier'])) {
    $id=(int)($_POST['supplier_id']??0); $name=trim($_POST['supplier_name']??''); $code=trim($_POST['supplier_code']??'');
    $contact=trim($_POST['contact_person']??''); $phone=trim($_POST['phone']??''); $email=trim($_POST['email']??''); $address=trim($_POST['address']??'');
    $opening=max(0,(float)($_POST['opening_balance']??0)); $status=(int)($_POST['status']??1);
    if ($name==='') { $msg='Supplier name is required.'; $msgType='error'; }
    else {
        try {
            if ($id>0) { $s=$conn->prepare("UPDATE suppliers SET supplier_code=NULLIF(?,''),supplier_name=?,contact_person=?,phone=?,email=?,address=?,opening_balance=?,status=? WHERE supplier_id=?"); $s->bind_param('ssssssdii',$code,$name,$contact,$phone,$email,$address,$opening,$status,$id); }
            else { $s=$conn->prepare("INSERT INTO suppliers (supplier_code,supplier_name,contact_person,phone,email,address,opening_balance,status) VALUES (NULLIF(?,''),?,?,?,?,?,?,?)"); $s->bind_param('ssssssdi',$code,$name,$contact,$phone,$email,$address,$opening,$status); }
            $s->execute(); $s->close(); $msg='Supplier saved successfully.'; $msgType='success';
        } catch(Throwable $e) { $msg=$e->getCode()===1062?'Supplier code already exists.':$e->getMessage(); $msgType='error'; }
    }
}
$edit=null; if(isset($_GET['edit'])){$id=(int)$_GET['edit'];$q=$conn->prepare("SELECT * FROM suppliers WHERE supplier_id=?");$q->bind_param('i',$id);$q->execute();$edit=$q->get_result()->fetch_assoc();$q->close();}
$suppliers=$conn->query("SELECT s.*,COALESCE(SUM(CASE WHEN p.status<>'cancelled' THEN p.total_amount-p.paid_amount ELSE 0 END),0)+s.opening_balance balance,COUNT(p.purchase_id) purchase_count FROM suppliers s LEFT JOIN purchases p ON p.supplier_id=s.supplier_id GROUP BY s.supplier_id ORDER BY s.supplier_name");
$summary=$conn->query("SELECT COUNT(*) total,COALESCE(SUM(status=1),0) active,COALESCE(SUM(opening_balance),0) opening FROM suppliers")->fetch_assoc();
$payable=$conn->query("SELECT COALESCE(SUM(total_amount-paid_amount),0) v FROM purchases WHERE status<>'cancelled'")->fetch_assoc()['v'];
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Suppliers - Supun ERP</title><link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Lora:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><style><?php include 'shared_style.php'; include 'erp_style.php'; ?></style></head><body>
<?php include 'shared_nav.php'; ?><main class="main"><?php include 'shared_topbar.php'; ?><div class="content">
<div class="page-header"><div><h1 class="page-title-h"><i class="fa-solid fa-truck-field"></i> Suppliers</h1><p class="page-sub">Supplier contacts, purchase history and outstanding balances</p></div><div class="quick-links"><a class="btn-primary" href="purchases.php?new=1"><i class="fa-solid fa-cart-flatbed"></i> New Purchase</a></div></div>
<?php if($msg):?><div class="alert <?php echo $msgType;?>"><?php echo htmlspecialchars($msg);?></div><?php endif;?>
<div class="erp-stats"><div class="erp-stat"><span>Total Suppliers</span><strong><?php echo (int)$summary['total'];?></strong></div><div class="erp-stat green"><span>Active Suppliers</span><strong><?php echo (int)$summary['active'];?></strong></div><div class="erp-stat amber"><span>Total Payable</span><strong>Rs. <?php echo number_format((float)$payable,2);?></strong></div><div class="erp-stat"><span>Opening Balances</span><strong>Rs. <?php echo number_format((float)$summary['opening'],2);?></strong></div></div>
<div class="erp-grid"><section class="card"><div class="card-head"><h4><i class="fa-solid fa-address-card"></i> <?php echo $edit?'Edit':'Add';?> Supplier</h4></div><form method="post" class="erp-form"><input type="hidden" name="supplier_id" value="<?php echo (int)($edit['supplier_id']??0);?>"><div class="form-grid">
<div class="field"><label>Supplier Code</label><input class="inp" name="supplier_code" value="<?php echo htmlspecialchars($edit['supplier_code']??'');?>" placeholder="SUP-001"></div><div class="field"><label>Status</label><select class="inp" name="status"><option value="1">Active</option><option value="0" <?php echo isset($edit)&&!(int)$edit['status']?'selected':'';?>>Inactive</option></select></div>
<div class="field full"><label>Supplier Name *</label><input class="inp" name="supplier_name" required value="<?php echo htmlspecialchars($edit['supplier_name']??'');?>"></div><div class="field full"><label>Contact Person</label><input class="inp" name="contact_person" value="<?php echo htmlspecialchars($edit['contact_person']??'');?>"></div><div class="field"><label>Phone</label><input class="inp" name="phone" value="<?php echo htmlspecialchars($edit['phone']??'');?>"></div><div class="field"><label>Email</label><input class="inp" type="email" name="email" value="<?php echo htmlspecialchars($edit['email']??'');?>"></div><div class="field full"><label>Address</label><textarea class="inp" name="address"><?php echo htmlspecialchars($edit['address']??'');?></textarea></div><div class="field full"><label>Opening Payable Balance (Rs.)</label><input class="inp" type="number" min="0" step="0.01" name="opening_balance" value="<?php echo htmlspecialchars($edit['opening_balance']??'0');?>"></div></div><div class="actions"><button class="btn-primary" name="save_supplier"><i class="fa-solid fa-floppy-disk"></i> Save Supplier</button><?php if($edit):?><a class="btn-secondary" href="suppliers.php">Cancel</a><?php endif;?></div></form></section>
<section class="card table-card-full"><div class="card-head"><h4><i class="fa-solid fa-list"></i> Supplier Directory</h4><span class="count-badge"><?php echo (int)$summary['total'];?> suppliers</span></div><div class="tbl-wrap"><table><thead><tr><th>Supplier</th><th>Contact</th><th>Purchases</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($s=$suppliers->fetch_assoc()):?><tr><td><strong><?php echo htmlspecialchars($s['supplier_name']);?></strong><div class="muted"><?php echo htmlspecialchars($s['supplier_code']?:'No code');?></div></td><td><?php echo htmlspecialchars($s['phone']?:'-');?><div class="muted"><?php echo htmlspecialchars($s['email']?:'');?></div></td><td><?php echo (int)$s['purchase_count'];?></td><td class="money">Rs. <?php echo number_format((float)$s['balance'],2);?></td><td><span class="status-pill <?php echo $s['status']?'active':'cancelled';?>"><?php echo $s['status']?'Active':'Inactive';?></span></td><td><div class="table-actions"><a class="btn-small" href="?edit=<?php echo (int)$s['supplier_id'];?>"><i class="fa-solid fa-pen"></i> Edit</a><a class="btn-small" href="purchases.php?supplier=<?php echo (int)$s['supplier_id'];?>"><i class="fa-solid fa-clock-rotate-left"></i> Purchases</a></div></td></tr><?php endwhile;?></tbody></table></div></section></div>
</div></main></body></html>
