SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE roles (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(80) NOT NULL, permissions JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE users (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, role_id BIGINT UNSIGNED NOT NULL, display_name VARCHAR(120) NOT NULL, email VARCHAR(190) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, phone VARCHAR(30), status ENUM('active','inactive') DEFAULT 'active', last_login_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id)) ENGINE=InnoDB;
CREATE TABLE login_history (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, user_id BIGINT UNSIGNED, login_at DATETIME NOT NULL, logout_at DATETIME NULL, ip_address VARCHAR(45), user_agent VARCHAR(500), FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE audit_logs (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, user_id BIGINT UNSIGNED NULL, actor_name VARCHAR(120) NOT NULL, action_type VARCHAR(80) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id BIGINT UNSIGNED NULL, old_values JSON NULL, new_values JSON NULL, ip_address VARCHAR(45), user_agent VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(entity_type,entity_id), FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;

CREATE TABLE categories (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) UNIQUE NOT NULL, status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE brands (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) UNIQUE NOT NULL, status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE products (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, item_code VARCHAR(80) UNIQUE NOT NULL, name VARCHAR(190) NOT NULL, barcode VARCHAR(100) UNIQUE NULL, brand_id BIGINT UNSIGNED NULL, category_id BIGINT UNSIGNED NULL, model VARCHAR(100), unit VARCHAR(30) DEFAULT 'PCS', avg_cost DECIMAL(18,4) DEFAULT 0, retail_price DECIMAL(18,2) DEFAULT 0, wholesale_price DECIMAL(18,2) DEFAULT 0, minimum_stock DECIMAL(14,3) DEFAULT 0, current_stock DECIMAL(14,3) DEFAULT 0, warranty_months INT DEFAULT 0, serial_tracking BOOLEAN DEFAULT FALSE, rack_location VARCHAR(100), status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(name), INDEX(current_stock), FOREIGN KEY(brand_id) REFERENCES brands(id), FOREIGN KEY(category_id) REFERENCES categories(id)) ENGINE=InnoDB;
CREATE TABLE product_serials (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, product_id BIGINT UNSIGNED NOT NULL, serial_number VARCHAR(190) UNIQUE NOT NULL, status ENUM('in_stock','sold','returned','damaged','supplier_return') DEFAULT 'in_stock', warranty_start DATE NULL, warranty_end DATE NULL, purchase_item_id BIGINT UNSIGNED NULL, sale_item_id BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;

CREATE TABLE customers (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, customer_code VARCHAR(60) UNIQUE NOT NULL, name VARCHAR(160) NOT NULL, business_name VARCHAR(160), phone VARCHAR(30), email VARCHAR(190), address TEXT, customer_type ENUM('retail','wholesale','both') DEFAULT 'retail', credit_enabled BOOLEAN DEFAULT FALSE, default_payment_period VARCHAR(30) DEFAULT '30_days', outstanding DECIMAL(18,2) DEFAULT 0, total_sales DECIMAL(18,2) DEFAULT 0, total_payments DECIMAL(18,2) DEFAULT 0, last_purchase_at DATETIME NULL, last_payment_at DATETIME NULL, status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(name), INDEX(phone)) ENGINE=InnoDB;
CREATE TABLE suppliers (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, supplier_code VARCHAR(60) UNIQUE NOT NULL, name VARCHAR(160) NOT NULL, phone VARCHAR(30), email VARCHAR(190), address TEXT, outstanding DECIMAL(18,2) DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

CREATE TABLE purchases (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, purchase_no VARCHAR(60) UNIQUE NOT NULL, supplier_id BIGINT UNSIGNED NOT NULL, supplier_invoice VARCHAR(100) NOT NULL, purchase_date DATE NOT NULL, payment_type ENUM('cash','credit') NOT NULL, subtotal DECIMAL(18,2) NOT NULL, discount DECIMAL(18,2) DEFAULT 0, tax DECIMAL(18,2) DEFAULT 0, total DECIMAL(18,2) NOT NULL, paid_amount DECIMAL(18,2) DEFAULT 0, balance DECIMAL(18,2) DEFAULT 0, due_date DATE NULL, payment_method VARCHAR(40), notes TEXT, status ENUM('draft','posted','cancelled','returned') DEFAULT 'posted', created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(supplier_id,supplier_invoice), FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE purchase_items (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, purchase_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, quantity DECIMAL(14,3) NOT NULL, unit_cost DECIMAL(18,4) NOT NULL, discount DECIMAL(18,2) DEFAULT 0, tax DECIMAL(18,2) DEFAULT 0, line_total DECIMAL(18,2) NOT NULL, FOREIGN KEY(purchase_id) REFERENCES purchases(id), FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;

CREATE TABLE sales (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sale_no VARCHAR(60) UNIQUE NOT NULL, customer_id BIGINT UNSIGNED NULL, sale_date DATETIME NOT NULL, sale_type ENUM('retail','wholesale') NOT NULL, payment_type ENUM('cash','credit') NOT NULL, subtotal DECIMAL(18,2) NOT NULL, discount DECIMAL(18,2) DEFAULT 0, total DECIMAL(18,2) NOT NULL, paid_amount DECIMAL(18,2) DEFAULT 0, balance DECIMAL(18,2) DEFAULT 0, due_date DATE NULL, status ENUM('unpaid','partially_paid','paid','overdue','cancelled','returned') NOT NULL, notes TEXT, created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(sale_date), INDEX(status), FOREIGN KEY(customer_id) REFERENCES customers(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE sale_items (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sale_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, quantity DECIMAL(14,3) NOT NULL, unit_price DECIMAL(18,2) NOT NULL, historical_unit_cost DECIMAL(18,4) NOT NULL, discount DECIMAL(18,2) DEFAULT 0, warranty_months INT DEFAULT 0, line_total DECIMAL(18,2) NOT NULL, gross_profit DECIMAL(18,2) NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(id), FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;
CREATE TABLE sale_payments (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sale_id BIGINT UNSIGNED NOT NULL, method ENUM('cash','card','bank_transfer','cheque','other') NOT NULL, amount DECIMAL(18,2) NOT NULL, reference_no VARCHAR(100), FOREIGN KEY(sale_id) REFERENCES sales(id)) ENGINE=InnoDB;

CREATE TABLE customer_payments (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, receipt_no VARCHAR(60) UNIQUE NOT NULL, customer_id BIGINT UNSIGNED NOT NULL, payment_date DATETIME NOT NULL, amount DECIMAL(18,2) NOT NULL, method VARCHAR(40) NOT NULL, reference_no VARCHAR(100), allocation_mode ENUM('single','multiple','oldest','advance') NOT NULL, notes TEXT, collected_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(customer_id) REFERENCES customers(id), FOREIGN KEY(collected_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE customer_payment_allocations (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, payment_id BIGINT UNSIGNED NOT NULL, sale_id BIGINT UNSIGNED NOT NULL, amount DECIMAL(18,2) NOT NULL, FOREIGN KEY(payment_id) REFERENCES customer_payments(id), FOREIGN KEY(sale_id) REFERENCES sales(id)) ENGINE=InnoDB;
CREATE TABLE customer_opening_balances (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, customer_id BIGINT UNSIGNED NOT NULL, opening_date DATE NOT NULL, amount DECIMAL(18,2) NOT NULL, notes VARCHAR(255), created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(customer_id) REFERENCES customers(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE supplier_payments (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, payment_no VARCHAR(60) UNIQUE NOT NULL, supplier_id BIGINT UNSIGNED NOT NULL, purchase_id BIGINT UNSIGNED NULL, payment_date DATETIME NOT NULL, amount DECIMAL(18,2) NOT NULL, method VARCHAR(40) NOT NULL, reference_no VARCHAR(100), notes TEXT, created_by BIGINT UNSIGNED NOT NULL, FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(purchase_id) REFERENCES purchases(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;

CREATE TABLE stock_movements (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, product_id BIGINT UNSIGNED NOT NULL, movement_type ENUM('purchase','cash_sale','credit_sale','sales_return','purchase_return','damaged','adjustment','opening','transfer') NOT NULL, quantity DECIMAL(14,3) NOT NULL, unit_cost DECIMAL(18,4) NOT NULL, running_quantity DECIMAL(14,3) NOT NULL, reference_type VARCHAR(40), reference_id BIGINT UNSIGNED, notes TEXT, approved_by BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(product_id,created_at), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(approved_by) REFERENCES users(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE returns (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, return_no VARCHAR(60) UNIQUE NOT NULL, return_type ENUM('sale','purchase') NOT NULL, reference_id BIGINT UNSIGNED NOT NULL, return_date DATETIME NOT NULL, reason VARCHAR(255), resolution ENUM('refund','credit_note','exchange','supplier_credit') NOT NULL, total DECIMAL(18,2) NOT NULL, status ENUM('pending','approved','rejected','posted') DEFAULT 'pending', approved_by BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(approved_by) REFERENCES users(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE return_items (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, return_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, quantity DECIMAL(14,3) NOT NULL, unit_price DECIMAL(18,2) NOT NULL, historical_unit_cost DECIMAL(18,4) NOT NULL, condition_type ENUM('resalable','damaged','warranty') NOT NULL, FOREIGN KEY(return_id) REFERENCES returns(id), FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB;

CREATE TABLE expense_categories (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) UNIQUE NOT NULL) ENGINE=InnoDB;
CREATE TABLE accounts (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120) NOT NULL, account_type ENUM('cash','bank') NOT NULL, account_number VARCHAR(100), opening_balance DECIMAL(18,2) DEFAULT 0, current_balance DECIMAL(18,2) DEFAULT 0, status ENUM('active','inactive') DEFAULT 'active') ENGINE=InnoDB;
CREATE TABLE expenses (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, expense_no VARCHAR(60) UNIQUE NOT NULL, category_id BIGINT UNSIGNED NOT NULL, account_id BIGINT UNSIGNED NOT NULL, expense_date DATE NOT NULL, amount DECIMAL(18,2) NOT NULL, payee VARCHAR(160), reference_no VARCHAR(100), notes TEXT, created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES expense_categories(id), FOREIGN KEY(account_id) REFERENCES accounts(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE account_transactions (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, account_id BIGINT UNSIGNED NOT NULL, transaction_date DATETIME NOT NULL, direction ENUM('in','out') NOT NULL, amount DECIMAL(18,2) NOT NULL, reference_type VARCHAR(50), reference_id BIGINT UNSIGNED, description VARCHAR(255), created_by BIGINT UNSIGNED NOT NULL, FOREIGN KEY(account_id) REFERENCES accounts(id), FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE daily_cash_closings (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, closing_date DATE UNIQUE NOT NULL, expected_cash DECIMAL(18,2) NOT NULL, counted_cash DECIMAL(18,2) NOT NULL, variance DECIMAL(18,2) NOT NULL, notes TEXT, closed_by BIGINT UNSIGNED NOT NULL, closed_at DATETIME NOT NULL, FOREIGN KEY(closed_by) REFERENCES users(id)) ENGINE=InnoDB;

CREATE TABLE import_batches (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, filename VARCHAR(255) NOT NULL, status ENUM('uploaded','validated','posted','failed','rolled_back') NOT NULL, valid_rows INT DEFAULT 0, warning_rows INT DEFAULT 0, error_rows INT DEFAULT 0, options JSON NULL, error_report_path VARCHAR(255), imported_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, posted_at DATETIME NULL, FOREIGN KEY(imported_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE import_batch_rows (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, batch_id BIGINT UNSIGNED NOT NULL, excel_row INT NOT NULL, supplier_code VARCHAR(60) NOT NULL, supplier_name VARCHAR(160) NOT NULL, supplier_phone VARCHAR(30), supplier_invoice VARCHAR(100) NOT NULL, purchase_date DATE NOT NULL, item_code VARCHAR(80) NOT NULL, product_name VARCHAR(190) NOT NULL, barcode VARCHAR(100), serial_number VARCHAR(190), brand VARCHAR(100), unit VARCHAR(30), category VARCHAR(100), cost_price DECIMAL(18,4) NOT NULL, retail_price DECIMAL(18,2) NOT NULL, wholesale_price DECIMAL(18,2) NOT NULL, purchase_quantity DECIMAL(14,3) NOT NULL, validation_status ENUM('valid','warning','error') NOT NULL, messages TEXT, raw_data JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(batch_id) REFERENCES import_batches(id)) ENGINE=InnoDB;
CREATE TABLE approvals (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, approval_type ENUM('price_change','discount','sale_return','stock_adjustment','negative_stock') NOT NULL, entity_type VARCHAR(50), entity_id BIGINT UNSIGNED, requested_values JSON NOT NULL, status ENUM('pending','approved','rejected') DEFAULT 'pending', requested_by BIGINT UNSIGNED NOT NULL, reviewed_by BIGINT UNSIGNED NULL, requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, reviewed_at DATETIME NULL, notes TEXT, FOREIGN KEY(requested_by) REFERENCES users(id), FOREIGN KEY(reviewed_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value TEXT, updated_by BIGINT UNSIGNED NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(updated_by) REFERENCES users(id)) ENGINE=InnoDB;

CREATE VIEW customer_ledger AS SELECT s.customer_id, s.sale_date entry_date, s.sale_no reference, 'Credit sale' description, s.total debit, 0 credit FROM sales s WHERE s.payment_type='credit' AND s.status NOT IN ('cancelled','returned') UNION ALL SELECT p.customer_id, p.payment_date, p.receipt_no, 'Customer payment', 0, p.amount FROM customer_payments p UNION ALL SELECT o.customer_id,o.opening_date,CONCAT('OPEN-',o.id),'Opening credit balance',o.amount,0 FROM customer_opening_balances o;
CREATE VIEW product_profitability AS SELECT p.id,p.item_code,p.name,p.avg_cost,p.retail_price,p.wholesale_price,p.current_stock,(p.retail_price-p.avg_cost) retail_profit,(CASE WHEN p.retail_price=0 THEN 0 ELSE (p.retail_price-p.avg_cost)/p.retail_price*100 END) retail_margin_pct,(CASE WHEN p.avg_cost=0 THEN 0 ELSE (p.retail_price-p.avg_cost)/p.avg_cost*100 END) retail_markup_pct,(p.wholesale_price-p.avg_cost) wholesale_profit FROM products p;

SET FOREIGN_KEY_CHECKS=1;
